#!/bin/bash
if [ -z "$1" ]; then
	echo Usage: ./mux \<basename\>
	exit
fi
PP=/opt/janus/bin/janus-pp-rec
FFMPEG=/usr/bin/ffmpeg
RM=/bin/rm
AUDIO=${1}-audio.mjr
VIDEO=${1}-video.mjr
$PP $AUDIO ${1}-audio.opus
$PP $VIDEO ${1}-video.mp4
$FFMPEG -i ${1}-video.mp4 -i ${1}-audio.opus -c:v copy -c:a aac -strict experimental ${1}.mp4
$RM -f ${1}-audio.* ${1}-video.*
